events { worker_connections 1024; }

http {
    upstream facultades { server ms-facultades:8080; }
    upstream investigadores { server ms-investigadores:8080; }
    upstream investigaciones { server ms-investigaciones:8080; }

    server {
        listen 80;

        location /api/facultades {
            proxy_pass http://facultades;
        }

        location /api/investigadores {
            proxy_pass http://investigadores;
        }

        location /api/investigaciones {
            proxy_pass http://investigaciones;
        }
    }
}