events { worker_connections 1024; }

http {
    upstream facultades { server ms-facultades:8080; }
    upstream investigadores { server ms-investigadores:8081; }

    upstream investigaciones { server ms-investigaciones:8082; }

    server {
        listen 80;

        location /facultades {
            proxy_pass http://facultades;
            proxy_set_header Host $host;
        }

        location /carreras {
            proxy_pass http://facultades;
            proxy_set_header Host $host;
        }

        location /investigadores {
            proxy_pass http://investigadores;
            proxy_set_header Host $host;
        }


        location /investigaciones {
            proxy_pass http://investigaciones;
            proxy_set_header Host $host;
        }
    }
}