micronaut.application.name=ms-investigaciones

micronaut.server.port=8082

datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
datasources.default.driver-class-name=org.postgresql.Driver

datasources.default.url=jdbc:postgresql://db_investigaciones:5432/investigaciones_db
datasources.default.username=user_admin
datasources.default.password=password123

jpa.default.properties.hibernate.hbm2ddl.auto=update