micronaut.application.name=ms-investigadores

micronaut.server.port=8081

datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.url=jdbc:postgresql://db_investigadores:5432/investigadores_db
datasources.default.username=user_admin
datasources.default.password=password123

jpa.default.properties.hibernate.hbm2ddl.auto=update